Repository AY2425S1-CS2103T-F15-3/tp, pull requests merged in 2024-11, with the labels that each got.

#137 Create SortCommand feature v2
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.High

#168 Add autocomplete feature for command name
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: type.Story, priority.High

#146 Add value proposition in User Guide
  docs/UserGuide.md
Labels: alpha-bug, type.DocumentationBug

#148 Add table of contents to UserGuide
  docs/UserGuide.md
Labels: alpha-bug, type.DocumentationBug

#151 Update findTagCommandTest
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/FindTagCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: alpha-bug, type.FunctionalityBug

#184 Add more tag types for Person and Property
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ListingAddCommand.java
  src/main/java/seedu/address/model/tag/PersonTag.java
  src/main/java/seedu/address/model/tag/PersonTagType.java
  src/main/java/seedu/address/model/tag/PropertyTag.java
  src/main/java/seedu/address/model/tag/PropertyTagType.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: alpha-bug

#183 Show command suggestions to user when entering commands
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/Extensions.css
Labels: type.Enhancement, priority.Medium

#180 Implement export command
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/CsvUtil.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/AddressBookStorage.java
  src/main/java/seedu/address/storage/CsvAdaptedPerson.java
  src/main/java/seedu/address/storage/CsvSerializableAddressBook.java
  src/main/java/seedu/address/storage/MultiFormatAddressBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/data/MultiFormatAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/MultiFormatAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/MultiFormatAddressBookStorageTest/notJsonFormatAddressBook.json
  src/test/java/seedu/address/commons/util/JsonUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/MultiFormatAddressBookStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Task, priority.Medium

#190 Add tag styling to PersonPane
  src/main/java/seedu/address/ui/PersonPane.java
Labels: severity.VeryLow, alpha-bug, type.FeatureFlaw

#192 Fix formatting for sort command
  docs/UserGuide.md
Labels: alpha-bug, type.DocumentationBug

#195 Update help command sceenshot in UserGuide
  docs/UserGuide.md
  docs/images/helpMessage.png
  docs/images/helpMessage2.png
Labels: alpha-bug, type.DocumentationBug

#194 Update table of contents and command summary in UG
  docs/UserGuide.md
Labels: severity.VeryLow, alpha-bug, type.DocumentationBug

#196 Update user guide
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/developer-guide-images/ArchitectureDiagram.png
  docs/images/developer-guide-images/ArchitectureSequenceDiagram.png
  docs/images/developer-guide-images/BetterModelClassDiagram.png
  docs/images/developer-guide-images/CommitActivityDiagram.png
  docs/images/developer-guide-images/ComponentManagers.png
  docs/images/developer-guide-images/DeleteSequenceDiagram.png
  docs/images/developer-guide-images/LogicClassDiagram.png
  docs/images/developer-guide-images/LogicStorageDIP.png
  docs/images/developer-guide-images/ModelClassDiagram.png
  docs/images/developer-guide-images/ParserClasses.png
  docs/images/developer-guide-images/ShowSequenceDiagram.png
  docs/images/developer-guide-images/StorageClassDiagram.png
  docs/images/developer-guide-images/UiClassDiagram.png
  docs/images/developer-guide-images/UndoRedoState0.png
  docs/images/developer-guide-images/UndoRedoState1.png
  docs/images/developer-guide-images/UndoRedoState2.png
  docs/images/developer-guide-images/UndoRedoState3.png
  docs/images/developer-guide-images/UndoRedoState4.png
  docs/images/developer-guide-images/UndoRedoState5.png
  docs/images/developer-guide-images/UndoSequenceDiagram-Logic.png
  docs/images/developer-guide-images/UndoSequenceDiagram-Model.png
  docs/images/developer-guide-images/request_access.png
  docs/images/findCommand.png
  docs/images/findtagCommand.png
  docs/images/showCommand.png
  docs/images/user-guide-images/AddCommandShowcase.png
  docs/images/user-guide-images/ClearCommandShowcase.png
  docs/images/user-guide-images/DeleteCommandShowcase.png
  docs/images/user-guide-images/EditCommandShowcase.png
  docs/images/user-guide-images/ExportCommandShowcase.png
  docs/images/user-guide-images/FindAlexDavidResult.png
  docs/images/user-guide-images/FindtagCommandShowcase.png
  docs/images/user-guide-images/GeneralFindCommandShowcase.png
  docs/images/user-guide-images/HelpCommandShowcase.png
  docs/images/user-guide-images/HelpMessageShowcase.png
  docs/images/user-guide-images/HelpMessageShowcase2.png
  docs/images/user-guide-images/ListCommandShowcase.png
  docs/images/user-guide-images/ListingAddCommandShowcase.png
  docs/images/user-guide-images/ListingDeleteCommandShowcase.png
  docs/images/user-guide-images/RemarkAddCommandShowcase.png
  docs/images/user-guide-images/RemarkRemoveCommandShowcase.png
  docs/images/user-guide-images/ShowCommandShowcase.png
  docs/images/user-guide-images/SortCommandShowcase.png
  docs/images/user-guide-images/SpecificFindCommandShowcase.png
  docs/images/user-guide-images/Ui.png
  docs/index.md
Labels: type.Task, alpha-bug

#206 Add Code Reuse Comments
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Remark.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
Labels: type.DocumentationBug

#208 Improve UI design
  src/main/java/seedu/address/ui/PersonPane.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/PersonPane.fxml
Labels: alpha-bug

#214 Fix Show Command Not Updating
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListingAddCommand.java
  src/main/java/seedu/address/logic/commands/ListingDeleteCommand.java
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/logic/parser/ListingAddCommandParser.java
  src/main/java/seedu/address/logic/parser/ListingDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/UniqueListingList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonPane.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
Labels: priority.High, alpha-bug

#211 Ensure command name suggestions give the closest match
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, severity.Low, alpha-bug

#218 Edit UG according to feedback
  docs/UserGuide.md
Labels: alpha-bug, type.DocumentationBug

#220 Improve UG Feature examples
  docs/UserGuide.md
Labels: alpha-bug, type.DocumentationBug

#204 Add tips in UG
  docs/UserGuide.md
Labels: alpha-bug, type.DocumentationBug

#225 Fix typo in javadoc
  src/main/java/seedu/address/logic/parser/ListingAddCommandParser.java
  src/main/java/seedu/address/logic/parser/ListingDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
Labels: severity.VeryLow, alpha-bug

#226 Fix Help & Exit Commands
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.High, alpha-bug

#223 Improve UI design for person information and command output
  src/main/java/seedu/address/ui/PersonPane.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/PersonPane.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Enhancement, severity.Low, alpha-bug

#224 Branch update exit logger
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, alpha-bug

#233 Fix UG Table of Contents typo
  docs/UserGuide.md
Labels: alpha-bug, type.DocumentationBug

#234 Enhance UserGuide.md - Remove Remarks notes + Link examples
  docs/UserGuide.md
Labels: type.DocumentationBug

#326 Add User Guide Essentials
  docs/UserGuide.md
Labels: priority.Medium

#324 Ped bug fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/user-guide-images/MultipleRemarkAddCommandShowcase.png
Labels: type.Task, type.Bug, priority.High

#328 Change Listing Command Format
  src/main/java/seedu/address/logic/parser/ListingCommandsParser.java
Labels: priority.High

#323 App Enhancements + UG/DG Enhancements
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/developer-guide-images/BetterModelClassDiagram.png
  docs/images/developer-guide-images/ModelClassDiagram.png
  docs/images/user-guide-images/ListingAddMultipleTagShowcase.png
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug

#333 Rename all visual instances of "person" to "client"
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListingAddCommand.java
  src/main/java/seedu/address/logic/commands/ListingDeleteCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/model/person/ContainsGeneralKeywordsPredicate.java
  src/main/java/seedu/address/model/person/ContainsSpecificKeywordsPredicate.java
Labels: type.Task

#332 UG improvements
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/user-guide-images/ClearCommandShowcase.png
  docs/images/user-guide-images/ExportCommandShowcase.png
  docs/images/user-guide-images/HelpCommandShowcase.png
  docs/images/user-guide-images/HelpMessageShowcase.png
  docs/images/user-guide-images/HelpMessageShowcase2.png
Labels: type.Task, type.DocumentationBug

#327 PE-d bug fix round 2
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/developer-guide-images/UiClassDiagram.png
  docs/images/user-guide-images/GeneralFindCommandShowcase.png
  docs/images/user-guide-images/SpecificFindCommandShowcase.png
Labels: priority.High

#334 Update Storage.java UML diagram
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/developer-guide-images/StorageClassDiagram.png
Labels: type.Task

#337 Fix renaming AB-3 to PROperty in the user guide print header
  docs/_sass/minima/_base.scss
Labels: type.DocumentationBug

#340 Improve and fix issues in the user guide
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  docs/_sass/minima/custom-styles.scss
Labels: type.DocumentationBug

#338 DeveloperGuide.md fixes (Draft)
  docs/DeveloperGuide.md
Labels: type.DocumentationBug

#341 Branch fix UG typos and rephrase select components
  docs/UserGuide.md
Labels: type.DocumentationBug

#342 Ped bug fix 3
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.DocumentationBug

#345 Minor edits in UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.DocumentationBug

#354 Improvements to formatting and fix errors in developer guide
  docs/DeveloperGuide.md
Labels: type.DocumentationBug
