Repository AY2425S1-CS2103T-F15-3/tp, pull requests merged in 2024-10, with the labels that each got.

#24 Add Bing's photo
  docs/buffwuff1712.png
Labels: priority.High

#36 Update photo for sayomaki
  docs/images/sayomaki.png
Labels: type.Task

#23 Update AboutUs page
  docs/AboutUs.md
Labels: priority.High

#38 Update AboutUs page for sayomaki
  docs/AboutUs.md
Labels: type.Task

#43 NEW update about us Xuen Ye
  docs/AboutUs.md
Labels: priority.High

#29 Update AboutUs page for Team and DG Non-Functional Requirements
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/Gemfile
  docs/Gemfile.lock
Labels: type.Task

#25 Update target user profile, value proposition and key user stories
  docs/DeveloperGuide.md
Labels: priority.High

#46 Update UI mockup and README
  README.md
  docs/images/Ui.png
Labels: priority.High

#51 Update use cases
  docs/DeveloperGuide.md
Labels: type.Task

#63 Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task

#60 Edit Add Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Task

#65 Add findtag functionality
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindTagCommandTest.java
  src/test/java/seedu/address/logic/parser/FindTagCommandParserTest.java
Labels: type.Task, priority.High

#64 Improve help feature and its GUI
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task

#68 Fix formatting for add command error message
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Task, severity.VeryLow

#69 Update help information
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, severity.Low

#62 Adds the Remark command for Customers
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#67 Add delete tag prefix for edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Enhancement

#80 Branch update user guide help command
  docs/UserGuide.md
Labels: type.Task, priority.High

#82 Branch remove references to ab3
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/UserGuide.md
  docs/index.md
Labels: type.Task, priority.High

#84 Reorder help command arrangement in User Guide
  docs/UserGuide.md
Labels: type.Task

#87 Fix Help Menu scrolling
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug

#85 Update Remark Command documentation in DevGuide, UserGuide and Help
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task

#91 Add findtag command description to UserGuide
  docs/UserGuide.md
Labels: type.Task, priority.High, severity.Low

#90 Update findtag command help message in HelpWindow
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task, priority.High

#88 Update help window for updated usage of edit command
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task, priority.High

#92 Update User Guide for edit command with delete tag usage
  docs/UserGuide.md
Labels: type.Task

#93 Update helpMessage.png to show in User Guide
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: type.Task

#101 Limit types of tags users can input
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/tag/PersonTag.java
  src/main/java/seedu/address/model/tag/PersonTagType.java
  src/main/java/seedu/address/model/tag/PropertyTag.java
  src/main/java/seedu/address/model/tag/PropertyTagType.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#102 Fix formatting issue for add command help description
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: severity.VeryLow

#104 Implements Listing Backend
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListingAddCommand.java
  src/main/java/seedu/address/logic/commands/ListingDeleteCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ListingAddCommandParser.java
  src/main/java/seedu/address/logic/parser/ListingCommandsParser.java
  src/main/java/seedu/address/logic/parser/ListingDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Listing.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/person/UniqueListingList.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateListingException.java
  src/main/java/seedu/address/model/person/exceptions/ListingNotFoundException.java
  src/main/java/seedu/address/model/tag/PropertyTag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTagCommandTest.java
  src/test/java/seedu/address/logic/commands/ListingAddCommandTest.java
  src/test/java/seedu/address/logic/commands/ListingDeleteCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#103 Add PersonPane and ShowCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListingDeleteCommand.java
  src/main/java/seedu/address/logic/commands/ShowCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ShowCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonPane.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonPane.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
Labels: priority.High

#107 Refactor command parsing
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: type.Task

#105 Branch better find
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/ContainsGeneralKeywordsPredicate.java
  src/main/java/seedu/address/model/person/ContainsSpecificKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/ContainsGeneralKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/ContainsSpecificKeywordsPredicateTest.java
Labels: type.Task, priority.High

#109 Enable assertions
  build.gradle
Labels: type.Task, priority.High

#111 Add assertions to parse in AddCommandParser
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: priority.High

#120 Include PersonPane in UiClassDiagram
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: type.Task

#117 Update ModelClassDiagram
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: type.Task

#123 Add show command to UserGuide summary
  docs/UserGuide.md
Labels: type.Task

#115 Add assertions to find command constructor
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/ContainsGeneralKeywordsPredicate.java
  src/main/java/seedu/address/model/person/ContainsSpecificKeywordsPredicate.java
Labels: type.Task

#119 Add assertions to ShowCommand
  src/main/java/seedu/address/logic/commands/ShowCommand.java
Labels: type.Task

#127 Fix Feature Block Highlighting for User Guide
  build.gradle
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#125 Add property tag colours in person list view
  src/main/java/seedu/address/model/tag/PersonTag.java
  src/main/java/seedu/address/model/tag/PropertyTag.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/Extensions.css
Labels: type.Enhancement, severity.VeryLow

#129 Updates user guide to add property listing commands
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findCommand.png
  docs/images/findtagCommand.png
  docs/images/showCommand.png
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High

#131 Add show command UML diagram
  docs/diagrams/ShowSequenceDiagram.puml
  docs/images/ShowSequenceDiagram.png
Labels: type.Task

#132 Fix UML diagram for Show Command
  docs/diagrams/ShowSequenceDiagram.puml
  docs/images/ShowSequenceDiagram.png
Labels: priority.High

#136 Refactor isValidSpecificFInd method
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/person/ContainsGeneralKeywordsPredicate.java
  src/main/java/seedu/address/model/person/ContainsSpecificKeywordsPredicate.java
Labels: type.Task

#144 Update showCommand picture in UserGuide
  docs/images/showCommand.png
Labels: alpha-bug, type.DocumentationBug

#139 Update help window content for exit, list and show commands in helpWindow
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ShowCommand.java
Labels: severity.Low, alpha-bug, type.DocumentationBug

#177 Rename references in logger files to PROperty
  src/main/java/seedu/address/commons/core/LogsCenter.java
Labels: alpha-bug, type.FeatureFlaw

#143 Update UI markup in UserGuide
  docs/images/Ui.png
Labels: alpha-bug, type.DocumentationBug

#174 Rename addressbook.json + logger name to PROperty
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: alpha-bug, type.DocumentationBug

#172 Update UserGuide.md findtag documentation
  docs/UserGuide.md
Labels: alpha-bug, type.DocumentationBug
